### ISSUE TITLE
Form data not submitted

### ISSUE THREAD

**Issue by dan-klasson** [ASnow/volt-slim#3]
I've been trying to get this to work. It seems that the below form does not get submitted with any value. And I am a bit stumped to why this is.

```
tpl-title Todos
tpl-body

  h1 Todos

  form e-submit="add_todo" role="form"
    div.form-group
      input.form-control type="text" value="#{ page._name }"

  table.todo-table
    - page._todos.each_with_index do |todo, index|
      tr
        td 
          = todo._name
        td
          button X
```

I've added the code directly in the Ruby console using `Volt::Slim::Compiler.build`, and it compiles fine. The `page._todos` array gets populated, but passed an empty string each time. 

If I swap out the slim template for the output of `build`, it works as expected. 

I'm using Volt 0.9.6

**Comment by ASnow** [comment]
I try this template, and submit form by Enter key. it works for me.

```
# controller code
    model :page
    def index
      page._todos ||= []
    end
    def add_todo
      name = page._name
      `console.log(name)`
      page._todos << {name: page._name}
    end
```

**Comment by ASnow** [comment]
Please write volt-slim gem version and console output if it has significant information

**Comment by dan-klasson** [comment]
Jesus, I had different variable names for the field value on the two templates. I was staring myself blind on that for an hour and did not spot it. Sorry to bother you.
